package javagameshow2;

import java.util.Random;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Igor
 */
public class Interface extends javax.swing.JFrame {

    private int totalRespondidas;
    private int totalAcertos;
    public Pergunta perguntaSorteada;
    
    public Interface() {
        initComponents();
        informativoLb.setVisible(false);
        getAlternativa.setVisible(false);
        btnResposta.setVisible(false);
        resultadoLb.setVisible(false);
        scoreLb.setVisible(false); 
    }

  
    public int getTotalRespondidas() {
        return totalRespondidas;
    }

    public void setTotalRespondidas(int totalRespondidas) {
        this.totalRespondidas = totalRespondidas;
    }

    public int getTotalAcertos() {
        return totalAcertos;
    }

    public void setTotalAcertos(int totalAcertos) {
        this.totalAcertos = totalAcertos;
    }
    
         
   
    
                                            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        perguntaLb = new javax.swing.JLabel();
        informativoLb = new javax.swing.JLabel();
        getAlternativa = new javax.swing.JTextField();
        scoreLb = new javax.swing.JLabel();
        alternativaLb = new javax.swing.JLabel();
        resultadoLb = new javax.swing.JLabel();
        btnResposta = new javax.swing.JButton();
        btnStart = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("               GAME JAVA");

        perguntaLb.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N

        informativoLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        informativoLb.setText("Digite a alternativa escolhida: ");

        scoreLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        scoreLb.setForeground(new java.awt.Color(0, 0, 255));

        alternativaLb.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        alternativaLb.setForeground(new java.awt.Color(255, 0, 0));

        resultadoLb.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        resultadoLb.setForeground(new java.awt.Color(255, 0, 0));

        btnResposta.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnResposta.setText("Responder");
        btnResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostaActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnStart.setText("Start Game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alternativaLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(perguntaLb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scoreLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(informativoLb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getAlternativa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResposta))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(resultadoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStart)
                .addGap(18, 18, 18)
                .addComponent(perguntaLb, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alternativaLb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informativoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAlternativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResposta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(resultadoLb, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreLb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostaActionPerformed
         
        
        
        btnResposta.setVisible(false);
        
        String resposta1 = getAlternativa.getText();
        if(resposta1.equals(perguntaSorteada.getResposta())){
            resultadoLb.setText("Resposta certa !!!");
            setTotalRespondidas(getTotalRespondidas() + 1);
            setTotalAcertos(getTotalAcertos() + 1);
        }else{
            resultadoLb.setText("Resposta errada !!!");
            setTotalRespondidas(getTotalRespondidas() + 1);
        }
        
        scoreLb.setText("Acertos: ("+getTotalAcertos()+"/"+getTotalRespondidas()+")");
        
        if(getTotalRespondidas() - getTotalAcertos() > 3 ){
            btnStart.setText("New game");
            perguntaLb.setText("GAME OVER!!! Vou errou mais de 3 questoes.");
            alternativaLb.setText(" ");
            informativoLb.setText(" ");
            btnResposta.setVisible(false);
            informativoLb.setVisible(false);
            getAlternativa.setVisible(false);
            resultadoLb.setVisible(false);
            scoreLb.setVisible(true);
            setTotalRespondidas(0);
            setTotalAcertos(0);
        }

    }//GEN-LAST:event_btnRespostaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        
        Jogador jogador1 = new Jogador();
        
        Random aleatorio = new Random();
        
        btnStart.setText("Proxima pergunta");
        
        int sorteado = 1 + aleatorio.nextInt(20);
        
        perguntaSorteada = (Pergunta)jogador1.hashPerguntas.get(sorteado);

        
        perguntaLb.setText(perguntaSorteada.getEnumciado());
        alternativaLb.setText(perguntaSorteada.getAlternativa());
        
        informativoLb.setText("Digite a alternativa escolhida: ");
        btnResposta.setVisible(true);
        informativoLb.setVisible(true);
        getAlternativa.setVisible(true);
        resultadoLb.setVisible(true);
        scoreLb.setVisible(true);
        resultadoLb.setText(" ");
        scoreLb.setText(" ");

    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);

            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alternativaLb;
    private javax.swing.JButton btnResposta;
    private javax.swing.JToggleButton btnStart;
    private javax.swing.JTextField getAlternativa;
    private javax.swing.JLabel informativoLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel perguntaLb;
    private javax.swing.JLabel resultadoLb;
    private javax.swing.JLabel scoreLb;
    // End of variables declaration//GEN-END:variables
}
